### ISSUE TITLE
Quali grafici di base predisporre?

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/COVID-19_Sicilia#13]
@picomiles @pigreco nella [pagina di riepilogo](https://opendatasicilia.github.io/COVID-19_Sicilia/), secondo voi, quali grafici di base non possono mancare?

Nella risposta - se possibile e facile - inserite anche un esempio visuale (basta uno screenshot); può essere utile a capire la proposta

**Comment by pigreco** [comment]
secondo me:

questo descrive province x province

![image](https://user-images.githubusercontent.com/7631137/78540819-ff77fa80-77f4-11ea-9744-19f81c099640.png)

sarebbe anche utile un riepilogo per regione, tipo cosi:

![image](https://user-images.githubusercontent.com/7631137/78540916-20d8e680-77f5-11ea-9f91-75f68182095e.png)

in modo da avere una idea provinciale e regionale in un unico posto.

**Comment by aborruso** [comment]
ok @pigreco il primo che può allora lo fa e lo inserisce in quella pagina

**Comment by aborruso** [comment]
@pigreco aggiunto https://opendatasicilia.github.io/COVID-19_Sicilia/#riepilogo-regionale-2

**Comment by aborruso** [comment]
aggiunti andamenti provinciali https://opendatasicilia.github.io/COVID-19_Sicilia/#variazione-casi-positivi-per-provincia

**Comment by pigreco** [comment]
ci vorrebbe un istogramma con ascisse le date e ordinate uno dei parametri medici (es: nuovi_positivi), e una combo-box per scegliere la provincia, qualcosa di simile:

![image](https://user-images.githubusercontent.com/7631137/78936951-d9ca4a00-7aaf-11ea-8f68-38b1a61beedc.png)

--
https://datawrapper.dwcdn.net/KTz9C/1/

idea di @picomiles

**Comment by picomiles** [comment]
Alla fine credo di esserci riuscito in qualche modo.
[https://datawrapper.dwcdn.net/ueZWX/1/](https://datawrapper.dwcdn.net/ueZWX/1/ )
![immagine](https://user-images.githubusercontent.com/13104/79045146-e498f200-7c09-11ea-892a-a3a416eca147.png)

**Comment by aborruso** [comment]
Ciao Nino,
e usare invece delle semplici linee, così vedi tutti subito e sopratutto puoi farti un'idea delle differenze?

@picomiles mi scrivi l'email con cui ti sei registrato su datawrapper, così ti aggiungo al gruppo opendatasicilia

**Comment by pigreco** [comment]
![image](https://user-images.githubusercontent.com/7631137/79004978-29635100-7b56-11ea-8f53-2dcccba4488a.png)

io aggiungerei altro rigo sotto a `38 su 100.000 abitanti` e scrivere
`1 abitante ogni 2631` (cioè 100.000/38) è più chiaro  e rende meglio l'idea secondo me.

**EDIT** basterebbe aggiungere alla query:

```sql
UNION ALL
SELECT * FROM
(SELECT
'1 ogni <b>' + CAST(cast(((SELECT sum(totale) FROM pop_res_20190101)/sum(totale_casi)) AS INTEGER) AS STRING) + '</b> abitanti' totale_casi,
'1 ogni <b>' + CAST(cast(((SELECT sum(totale) FROM pop_res_20190101)/sum(deceduti)) AS INTEGER) AS STRING) + '</b> abitanti' deceduti,
'1 ogni <b>' + CAST(cast(((SELECT sum(totale) FROM pop_res_20190101)/sum(guariti)) AS INTEGER) AS STRING) + '</b> abitanti' guariti
from covid19_com_prov_en_aggregati group by covid19_com_prov_en_aggregati.data
ORDER by data DESC LIMIT 1) valorepercentomila
```

e allineare i nomi della tabella e dei campi

**Comment by picomiles** [comment]
> Ciao Nino,
> e usare invece delle semplici linee, così vedi tutti subito e sopratutto puoi farti un'idea delle differenze?
 
Ciao Andrea, ho provato a seguire il tuo suggerimento ma mi pare che il risultato sia poco leggibile (viene fuori più che altro un groviglio di linee che si sovrappongono)

**Comment by pigreco** [comment]
Aggiungiamo anche questa semplice mappa?? (realizzata sempre con Datawrapper)

![image](https://user-images.githubusercontent.com/7631137/79047025-89b8c800-7c14-11ea-9a1d-a8fb3d9b1a71.png)


https://datawrapper.dwcdn.net/ux0r6/7/

```html
<iframe title="COVID-19 Sicilia: mappa riepilogo regionale" aria-label="choropleth map" id="datawrapper-chart-ux0r6" src="//datawrapper.dwcdn.net/ux0r6/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="400"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",function(a){if(void 0!==a.data["datawrapper-height"])for(var e in a.data["datawrapper-height"]){var t=document.getElementById("datawrapper-chart-"+e)||document.querySelector("iframe[src*='"+e+"']");t&&(t.style.height=a.data["datawrapper-height"][e]+"px")}})}();
</script>
```

**Comment by aborruso** [comment]
Per me ok @pigreco 
Grazie

**Comment by aborruso** [comment]
Procedo con la pubblicazione della #25 , proposta da Giulio

![image](https://user-images.githubusercontent.com/30607/79050570-1bcbcb00-7c2b-11ea-8927-2c540158fde5.png)

**Comment by aborruso** [comment]
Guenter Richter ha creato una bella visualizzazione, a partire dai dati da noi raccolti

La inserirei

![image](https://user-images.githubusercontent.com/30607/79217595-67f75500-7e4f-11ea-87d4-7c1d64168af7.png)

**Comment by pigreco** [comment]
Per me ok @aborruso 

grazie.

io quella mia non la metto, manca la possibilità dello sfondo su Datawrapper.
