### ISSUE TITLE
Ordine grafici sezione: "Confermati, deceduti e ospedalizzati per provincia"

### ISSUE THREAD

**Issue by pcmasuzzo** [opendatasicilia/COVID-19_Sicilia#14]
Non sarebbe più logico invertire i grafici in [questa sezione](https://opendatasicilia.github.io/COVID-19_Sicilia/#confermati-deceduti-e-ospedalizzati-per-provincia) secondo l'ordine
**Casi confermati | Ospedalizzati | Deceduti**?

Un "minor detail" senza dubbio, ma renderebbe la lettura più intuitiva.

**Comment by aborruso** [comment]
Ok allora lo farò pure sul [riepilogo generale](https://opendatasicilia.github.io/COVID-19_Sicilia/#riepilogo-regionale-1).

Grazie

**Comment by aborruso** [comment]
Grazie mille capo @pcmasuzzo , fatto!
