### ISSUE TITLE
Aggiungere un'introduzione

### ISSUE THREAD

**Issue by nelsonmau** [opendatasicilia/COVID-19_Sicilia#15]
L'utente che arriva legge un'introduzione in cui gli si spiega qual è il senso di questa pagina, chi la cura, che tipo di dati sono, come sono elaborati e perché

**Comment by pcmasuzzo** [comment]
I miei 20 cents:

Io lascerei la pagina cosi' come e', lasciando i grafici come prima cosa che l'utente vede (quindi aprendo con un sunto / sezione COVID-19: visualizzazioni di base, per la Sicilia - come adesso).

Il commento di @nelsonmau pero' makes sense, quindi prenderei semplicemente il [README](https://github.com/opendatasicilia/COVID-19_Sicilia/blob/master/README.md) (che contiene tutte le info a cui @nelsonmau si riferisce) e lo porterei nella landing page.

Come? Magari con una icona che rimanda al README:
![image](https://user-images.githubusercontent.com/10747332/78759479-f49da100-797f-11ea-9739-0720ae649a35.png)

oppure con tutto o parte del README che pero' possiamo nascondere. Temo che mettendo una intro troppo grande il messaggio dei grafici/dati venga diluito troppo.
