### ISSUE TITLE
Grafici: modificare il disclaimer

### ISSUE THREAD

**Issue by nelsonmau** [opendatasicilia/COVID-19_Sicilia#16]
Cambiare da `Fonte dati: OpenData Sicilia` in `Fonte dati: Elaborazione OpenData Sicilia. Fonte dati: Regione siciliana`. 

ODS non è la fonte...

**Comment by aborruso** [comment]
Ok, ho rielaborato come sotto.

@pigreco @nelsonmau che dite?

Come `Description`

```html
Un progetto di <a href="https://groups.google.com/forum/#!forum/opendatasicilia"">OpenDataSicilia</a>
```

Come `Notes` "Questo grafico viene aggiornato una volta al giorno"

Come `Data source`, "Regione Siciliana e Dipartimento Protezione Civile"

Come `Link to data source` "https://github.com/opendatasicilia/COVID-19_Sicilia"


![image](https://user-images.githubusercontent.com/30607/78750202-1000b000-7970-11ea-95e2-bb0b7545aec2.png)

**Comment by nelsonmau** [comment]
Come Data source, "Regione Siciliana e Dipartimento Protezione Civile, Elaborazioni di OpendataSicilia"
