### ISSUE TITLE
Inserire "Chiedi aiuto"

### ISSUE THREAD

**Issue by nelsonmau** [opendatasicilia/COVID-19_Sicilia#18]
Per facilitare i potenziali utilizzatori, inserire un bottone (proprio un <button>) con nome `Qualche dubbio? Chiedi aiuto`. L'utente lo clicca e manda una mail a info@opendatasicilia.it

**Comment by pigreco** [comment]
@nelsonmau 
quale dei due (hihihihi)

![image](https://user-images.githubusercontent.com/7631137/78916725-36b50880-7a8e-11ea-8410-161d603dc45e.png)

**Comment by aborruso** [comment]
Per ora minimale in alto
