### ISSUE TITLE
Aggiungere immagine opengraph e meta info

### ISSUE THREAD

**Issue by nelsonmau** [opendatasicilia/COVID-19_Sicilia#20]
per l'immagine allego img come possibile soluzione

![2020 04 08-opendatasicilia github io](https://user-images.githubusercontent.com/1769578/78749918-7d601100-796f-11ea-9a75-f1d53ee27885.png)

Per le meta info: 

- Title: Coronavirus in Sicilia: guarda i dati e i grafici aggiornati quotidianamente 
- Description: Monitora la diffusione del Covid 19 in tutte le province (Agrigento, Caltanissetta, Catania, Enna, Messina, Palermo, Ragusa, Siracusa, Trapani).

**Comment by aborruso** [comment]
@nelsonmau per ora la pagina è un file markdown, auto convertito in html da github.

Per fare quello che dici bisognerebbe cambiare o tutto in una semplice pagina HTML, o in un template jekyll/hugo.

Oggi non me ne posso occupare. La prima che sembra la più comoda, a mio avviso è molto scomoda (soltanto per inserire la sezione codice di embed).

**Comment by nelsonmau** [comment]
a sto punto allora è meglio lasciarla markdown e amen... per evitare inutili incasinamenti... tnx!
