### ISSUE TITLE
Velocità di raddoppio: spiegare che cos'è e perché è importante

### ISSUE THREAD

**Issue by nelsonmau** [opendatasicilia/COVID-19_Sicilia#21]
**sopra** il grafico "Velocità" di raddoppio andrebbe spiegato per bene che cos'è e perché è importante (forse aggiungere anche un link, oppure in maniera semplice chiederei a @pcmasuzzo di spiegare cos'è e perché è importante)

![2020 04 08-opendatasicilia github io](https://user-images.githubusercontent.com/1769578/78750542-bd73c380-7970-11ea-983b-02060552fc72.png)

**Comment by pcmasuzzo** [comment]
Volevo aprire anch'io una issue a tal proposito: a mio parere il link al blog post non e' sufficiente e ci vuole piu' informazione in questa sezione.

Ho guardato [questa query](https://github.com/opendatasicilia/COVID-19_Sicilia/blob/master/risorse/query/tempiRaddoppioContagiProvincia.sql).

Mi pare di capire si usi proprio la formula delineata nella sezione "How to calculate and apply doubling times" del [blog post linkato](https://blog.datawrapper.de/weekly-chart-coronavirus-doublingtimes/). @aborruso - mi confermi, per favore?

**Comment by aborruso** [comment]
> Mi pare di capire si usi proprio la formula delineata nella sezione "How to calculate and apply doubling times" del [blog post linkato](https://blog.datawrapper.de/weekly-chart-coronavirus-doublingtimes/). @aborruso - mi confermi, per favore?

Yes, capo, proprio quella. Che deriva da questo [concetto di base](https://www.wikiwand.com/en/Doubling_time) (che tu conoscerai già, non come me).

Per me non era chiusa, ma vado aggiungendo pezzi nel contesto complessivo, nel tempo che posso.

E grazie :)

**Comment by pcmasuzzo** [comment]
@nelsonmau controlli se OK con questa modifica? se si', feel free to close this ;-)
Grazie!

**Comment by nelsonmau** [comment]
sì è perfetto, grazie mille (ho imparato una cosa nuova e in realtà avevo aperto la issue per questo! :-)
