### ISSUE TITLE
Valorizzare la "Lettera aperta"...

### ISSUE THREAD

**Issue by nelsonmau** [opendatasicilia/COVID-19_Sicilia#22]
... rendendola più visibile

Ad esempio io ho fatto una prova di come farei...

![2020 04 08-opendatasicilia github io-nav](https://user-images.githubusercontent.com/1769578/78751725-0dec2080-7973-11ea-8745-1327930e65ca.png)

Se lo volete fare tale e quale ecco il codicillo

html
```
<body class="nimbus-is-editor">
    <div class="container-lg px-3 my-5 markdown-body">
        <nav id="lettera">
            <p>🛈 Leggi la nostra <strong>lettera aperta</strong> alla Regione Siciliana
            </p>        
        </nav>
...

```

css
```
nav#lettera {
    width:100%;
    padding:10px;
    background-color:#a3d3e35c;
    height:50px;
}
p {
    float:right;
}
```

**Comment by aborruso** [comment]
grazie

**Comment by pigreco** [comment]
Grazie per l'idea, la ho messa pure io nel mio repo di Enna

https://pigreco.github.io/COVID-19_Enna/
