### ISSUE TITLE
data decessi provincia di Agrigento

### ISSUE THREAD

**Issue by Davidejz** [opendatasicilia/COVID-19_Sicilia#24]
in data 24/03 sono presenti 2 decessi, nelle date successive viene indicato 1 solo decesso. Essendo una curva cumulata, che non indica l'incremento giornaliero, non dovrebbe sempre visualizzare 2 dopo la data 24/03?

**Comment by picomiles** [comment]
Quello che tu segnali è uno dei pochi (fortunatamente) casi di errore riscontrabili sul dataset. È ovvio purtroppo che non vi possono essere resuscitati (nonostante il periodo pasquale); è un errore rilevabile tra i dati [comunicati dalla Regione](http://pti.regione.sicilia.it/portal/page/portal/PIR_PORTALE/PIR_ArchivioLaRegioneInforma/PIR_CoronavirusaggiornamentoSicilia0325) analogo ad altri casi meno evidenti ma che riguardano i casi_totali (che non possono mai diminuire ma al più rimanere invariati) o i dimessi_guariti (alla cui diminuzione, come i dati evidenziano in qualche caso,  dovrebbe corrispondere un aumento tra i totali positivi (e in particolare tra gli ospedalizzati o tra i soggetti posti in isolamento domiciliare). Servirebbe un'interlocuzione con la Regione per capire come correggere questi (ripeto, fortunatamente) pochi casi.
A meno che non emerga qui una valida proposta alternativa.

**Comment by Davidejz** [comment]
@picomiles  è stato chiarissimo, grazie mille per la risposta!
