### ISSUE TITLE
Grafico "curva regioni" - COVID19 e riferimenti normativi

### ISSUE THREAD

**Issue by giuliodichiara** [opendatasicilia/COVID-19_Sicilia#25]
Relativamente alla produzione di un grafico che contenga la comparazione dei dati di tutte le regioni, così come discusso con @Davidejz e @aborruso, propongo l'inserimento di riferimenti normativi nel grafico, in uno schema simile a questo
![opendatasicilia](https://user-images.githubusercontent.com/8503662/79046773-1d899480-7c13-11ea-950e-c42ce4d4462d.png)

I riferimenti dei decreti attuativi li ho presi [da qui](https://www.studiocataldi.it/articoli/37721-coronavirus-tutti-i-provvedimenti-del-governo.asp) e li ho riassunti in:

- **DPCM 23 febbraio 2020**: misure di contenimento comuni zona rossa
- **DPCM 1 Marzo 2020**: misure di contenimento estese in Lombardia e Veneto, Emilia Romagna, Pesaro e Urbino
-  DPCM 4 Marzo 2020: chiusura attività didattiche a partire dal 5 Marzo
- **DPCM 8 Marzo 2020**: misure di contenimento estese in tutta Italia
- DPCM 11 Marzo 2020: chiusura di tutte le attività commerciali, con eccezioni

In grassetto quelle che utilizzerei nel grafico, per non appesantirlo nella lettura.

**Comment by aborruso** [comment]
@giuliodichiara  che te ne pare?

![image](https://user-images.githubusercontent.com/30607/79048687-22544580-7c1f-11ea-8ef7-0a8e455f4f1c.png)

**Comment by giuliodichiara** [comment]
Mi sembra perfetta.


Il sab 11 apr 2020, 18:06 Andrea Borruso <notifications@github.com> ha
scritto:
