### ISSUE TITLE
aggiungere sezione Chi usa il nostro progetto

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/COVID-19_Sicilia#26]

**Comment by pigreco** [comment]
fatto!

https://github.com/opendatasicilia/COVID-19_Sicilia#chi-usa-il-nostro-progetto

**Comment by aborruso** [comment]
Grazie

Ho aggiunto:

- link alla versione web archive dell'articolo Gazzetta, così ne abbiamo copia
- link al lavoro di @Davidejz
