### ISSUE TITLE
in alcuni grafici il link a Open Data Sicilia non funziona

### ISSUE THREAD

**Issue by picomiles** [opendatasicilia/COVID-19_Sicilia#27]
![immagine](https://user-images.githubusercontent.com/13104/79053867-e03bfb80-7c40-11ea-92db-bba2d6096994.png)
Funzionano praticamente solo i link del primo e del penultimo grafico nella pagina

**Comment by aborruso** [comment]
Sì, è un piccolo baco di datawrapper.

Per le tabelle i link sono gestiti correttamente, per i grafici è obbligatorio mettere il target "_blank".

Ad esempio

```
Un progetto di <a target="_blank" href="https://groups.google.com/forum/#!forum/opendatasicilia"">OpenDataSicilia</a>
```

@picomiles ho sistemato tutti, tranne il tuo che non hai inserito ancora nella cartella datawrapper del team ODS, quindi non lo posso editare.

L'ho provato svuotando cache browser e funziona.

Nino chiudi tu la issue quando per te è ok
