### ISSUE TITLE
Modifica Link esterni del grafico

### ISSUE THREAD

**Issue by nelsonmau** [opendatasicilia/COVID-19_Sicilia#28]
Nella descrizione di ogni grafico è attualmente previsto un link al google group, che non è utile.
Consiglio di:
- rimuovere il link al google group
- aggiungere il link a README del repo, così il `casalingo italiano` che vuole approfondisce il modo in cui i dati sono raccolti/trattati

mi permetto di segnalarlo come bug perché mi pare una cosa di sostanza, e non per fare critiche generiche. 

![2020 04 12-sicilia gazzettadelsud it](https://user-images.githubusercontent.com/1769578/79064054-d8fb0900-7ca5-11ea-83ce-e0d12393e815.png)

**Comment by aborruso** [comment]
@nelsonmau e se mettessi invece URL https://opendatasicilia.github.io/COVID-19_Sicilia/ ?

A me sembra quello più giusto rispetto all'obiettivo da te descritto.

Grazie

**Comment by nelsonmau** [comment]
Sì esatto, grazie

**Comment by aborruso** [comment]
grazie
