### ISSUE TITLE
sezione Parlano di questo progetto

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/COVID-19_Sicilia#31]
Aggiungiamo anche la sezione **Parlano di questo progetto** ??

ho trovato due casi:

1. **OnData** : https://twitter.com/ondatait/status/1249592682906816512
2. **persone** : https://twitter.com/AndreaDEramo70/status/1249634617822511106
3. **Petrusino**: https://twitter.com/petrusinoweb/status/1248554349728542720

**Comment by aborruso** [comment]
Ok, per me. Grazie
