### ISSUE TITLE
aggiungo stampe PDF atlas??

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/COVID-19_Sicilia#33]
In [questo ](https://github.com/pigreco/COVID19_Sicilia)repository ho realizzato un progetto QGIS con atlas e grafici dinamici, i dati sono quelli del [PCM-DPC](https://github.com/pcm-dpc/COVID-19) in particolare quelli provinciali.

La cartella `stampe` conterrà due PDF al giorno a partire da ieri:

1. PDF con 9 pagine, uno per provincia;
2. PDF complessivo regione/province

![image](https://user-images.githubusercontent.com/7631137/79488840-a5f4a480-801a-11ea-85b1-2d3dac2d1640.png)

![image](https://user-images.githubusercontent.com/7631137/79488881-bc026500-801a-11ea-9e2c-cfa75bca6010.png)

**Comment by aborruso** [comment]
Caro @pigreco mi sembra un arricchimento, un altro modo di divulgare dati locali.

Grazie
