### ISSUE TITLE
gsheet: aggiungere foglio per la licenza dati?

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/COVID-19_Sicilia#8]
Licenza:
--
[CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.it)

**Comment by aborruso** [comment]
Farei la semplice by.

Altrimenti se serve a qualche giornale, non è utilizzabile

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il sab 4 apr 2020, 14:28 Salvatore Fiandaca <notifications@github.com> ha
scritto:

**Comment by pigreco** [comment]
Ho messo, nello sheet `legenda` 

**CC-BY**

https://docs.google.com/spreadsheets/d/1wc9t8X7wRqmWfGCBwREi0b9DpbgpCPpmHpqoPTVyPXI/edit#gid=100363873
